---
# tasks file for grafana2
- name: Adding Grafana Repo
  copy: 
    src: grafana.rep
    dest: /etc/yum.repos.d/

- name: Install Grafana
  yum:
    name: grafana
    state: latest
    update_cache: yes

- name: Start grafana
  service:
    name: grafana-server
    state: started

- name: Add prometheus repo
  copy:
    src: prometheus.repo
    dest: /etc/yum.repos.d

- name: Install Prometheus
  yum:
    name: prometheus2
    state: latest
    update_cache: yes

- name: Start Prometheus
  service:
    name: prometheus
    state: started

- name: Add influxdb repo
  copy:
    src: influxdb.repo
    dest: /etc/yum.repos.d

- name: Install influxdb
  yum:
    name: influxdb
    state: latest
    update_cache: yes

- name: Start influxdb
  service:
    name: influxdb
    state: started
