---
# Install a docker for centos
yum:
  name: docker
  state: latest
  update_cache: yes

- name: pull elasticsearch img
  containers.podman.podman_image:
    name: docker.elastic.co/elasticsearch/elasticsearch:7.10.1

- name: Create elasticsearch network
  containers.podman.podman_network:
    name: elastic
    become: true

- name: Create container for elasticsearch
  containers.podman.podman_containers:
    containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
        state: present
        ports:
          - "9200:9200"
        networks:
          - name: elastic

- name: Pull kibana img
  containers.podman.podman_image:
    name: docker.elastic.co/kibana/kibana:7.10.1

- name: Create kibana container
  containers.podman.podman_containers:
    containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.10.1
        state: present
        ports:
          - "5601:5601"
        networks:
          - name: elastic

- name: Pull logstash container
  containers.podman.podman_containers:
    containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:7.10.1
        state: present
        ports:
          - "5044:5044"
        networks:
          - name: elastic
      
