---
# tasks file for grafana
- name: Get Packages of Grafana
  apt:
    deb: https://d1.grafana.com/oss/release/grafana_7.3.6_amd64.deb
    register: pkg_grafana

- name: Depackages Grafana
  dpkg_selections:
    name: grafana_7.3.6_amd64.deb
    selection: install
    when: pkg_grafana.changed

- name: Install libfontconfig
  apt:
    name: libfontconfig1
    state: latest
    update_cache: yes

- name: Install grafana
  apt:
    name: grafana
    state: latest
    update_cache: yes

- name: Install prometheus
  apt:
    name: prometheus
    state: latest
    update_cache: yes

- name: Start prometheus
  service:
    name: prometheus
    state: started

- name: Add Influxdata key
  apt_key:
    url: https://repos.influxdata.com/influxdb.key
    state: present

- name: Install Influxdb
  apt:
    name: influxdb
    state: latest
    update_cache: yes

- name: Start influxdb
  service:
    name: influxdb
    state: started
