---
# tasks file for roles/CentosDocker
- name: Installing Docker in Centos
  become: yes
  yum:
    name:
      - python
      - python3-pip
    state: present

- name: Installing Docker file
  become: yes
  yum: 
    name: docker
    state: latest
    update_cache: yes
  register: docker

- name: Installing Docker .py
  become: yes
  pip:
    name: docker.py
    state: latest
  when: docker.changed
