---
# tasks file for lamp1
 - name: Install apache
   apt:
     name: apache2
     state: latest
     update_cache: yes

- name: Add apache_index
  copy:
    content: "Hellow World"
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: '0644'
    register: apache_index

- name: Start apache2 service
  service:
    name: apache2
    state: restarted
    enabled: yes
    when: apache_index.changed

- name: whitelist apache2 in ufw
  ufw:
    rule: allow
    port: '80'
    proto: tcp

- name: Install mysql-server
  apt:
    name: mysql-server
    state: latest
    update_cache: yes

- name: Add mysql_index
  copy:
    content: "Hi World"
    dest: /var/www/html/index1.html
    owner: root
    group: root
    mode: '0644'
    register: mysql_index

- name: Start the mysql service
  service:
    name: mysql
    state: restarted
    enabled: yes
    when: mysql_index.changed

- name: install php
  apt:
    name:
      - php
      - php-mysql1
      - libapache2-mod-php
    state: latest
    update_cache: yes

- name: Add php_index
  copy:
    content: "Example content"
    dest: /var/www/html/index2.html
    owner: root
    group: root
    mode: '0644'
