---
- name: Install elasticsearch, kibana (elk) stack, logstash on ubuntu
  hosts: ubuntu
  roles:
    - ubuntu_elk

- name: Install elasticsearch, kibana (elk) stack, logstash on Centos
  hosts: centos
  roles:
    - elk_centos
